version: '3'
services:
  node-app:
    build:
     context: .
     args: 
      NODE_ENV : production
    ports:
      - 80:4000
    environment:
      - NODE_ENV=production
    command: npm run start

  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5434:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: nestjs

  # redis-db:
    #   image: redis:latest
    #   ports:
    #     - '6379:6379'
    # rcli:
    #   image: redis:latest
    #   links:
    #     - redis
    #   command: redis-cli -h redis